                                                                <div id="messages">
                                                                        Jin Ge, you've lived for
                                                                        <div id="elapseClock"></div>
                                                                </div>
                                                                <div id="loveu">
                                                                        Long live Master Jin, <br />
                                                                        We all love u forever and ever.<br />
                                                                        <span style="color:#FFFFFF">
                                                                                <big>